### PR TITLE
Remove created messages validation

### LINKED ISSUE #439: [POST /{{safeAddress}}/messages/ endpoint] status code 500 returned on successful sign
A status code 500 is returned when signing a message with a safe owner.

**Steps to reproduce:**

On a Goerli safe with test SAFE tokens, vote on this proposal on snapshot connected via WC safe app (a bit hard to reproduce, we can look into this together if needed).

**Actual result on nest cg:**

Message is signed but a status code 500 is returned:

https://github.com/safe-global/safe-client-gateway-nest/assets/92332710/7ad4cf8c-a4f9-4e4e-a2d4-5e4d28e367d0

Note: Once the message is signed is not valid anymore and will return a status code 400 if reused. This would be an example curl that returned a 500 on signature:

`curl 'https://safe-client-nest.staging.5afe.dev/v1/chains/5/safes/0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/messages' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Origin: https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev' \
  -H 'Referer: https://test_new_cgw_url--walletweb.review-wallet-web.5afe.dev/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"message":{"types":{"Vote":[{"name":"from","type":"address"},{"name":"space","type":"string"},{"name":"timestamp","type":"uint64"},{"name":"proposal","type":"bytes32"},{"name":"choice","type":"uint32"},{"name":"reason","type":"string"},{"name":"app","type":"string"},{"name":"metadata","type":"string"}],"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"}]},"domain":{"name":"snapshot","version":"0.1.4"},"primaryType":"Vote","message":{"from":"0x4127839cdf4f73d9fc9a2c2861d8d1799e9df40c","space":"tutis.eth","timestamp":"1686674868","proposal":"0x28c890a25e571c766b87cd05dffa30c654786cf32f849aba66dbf52d69ad3e70","choice":"4","reason":"","app":"snapshot","metadata":"{}"}},"signature":"0xf9fb2af217ff02fcacd1579f3ce1a8575883b8fefcab62da073ba170a8097a830f85fbdb128012826bca52669ace089377dda90d09e9f7cc9a8db789b061d29a1c","safeAppId":25}' \
  --compressed`

**Expected result:**
Same as on og client gateway. Here is a curl request from staging that did not throw any errors when signing:

`curl --location --request POST 'https://safe-client.staging.5afe.dev/v1/chains/5/safes/0x4127839cdf4F73d9fC9a2C2861d8d1799e9DF40C/messages' \
--header 'Accept: */*' \
--header 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'Connection: keep-alive' \
--header 'Origin: https://safe-wallet-web.staging.5afe.dev' \
--header 'Referer: https://safe-wallet-web.staging.5afe.dev/' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-site' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
--header 'content-type: application/json' \
--header 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"' \
--data '{
    "message": {
        "types": {
            "Vote": [
                {
                    "name": "from",
                    "type": "address"
                },
                {
                    "name": "space",
                    "type": "string"
                },
                {
                    "name": "timestamp",
                    "type": "uint64"
                },
                {
                    "name": "proposal",
                    "type": "bytes32"
                },
                {
                    "name": "choice",
                    "type": "uint32"
                },
                {
                    "name": "reason",
                    "type": "string"
                },
                {
                    "name": "app",
                    "type": "string"
                },
                {
                    "name": "metadata",
                    "type": "string"
                }
            ],
            "EIP712Domain": [
                {
                    "name": "name",
                    "type": "string"
                },
                {
                    "name": "version",
                    "type": "string"
                }
            ]
        },
        "domain": {
            "name": "snapshot",
            "version": "0.1.4"
        },
        "primaryType": "Vote",
        "message": {
            "from": "0x4127839cdf4f73d9fc9a2c2861d8d1799e9df40c",
            "space": "tutis.eth",
            "timestamp": "1686674123",
            "proposal": "0x28c890a25e571c766b87cd05dffa30c654786cf32f849aba66dbf52d69ad3e70",
            "choice": "4",
            "reason": "",
            "app": "snapshot",
            "metadata": "{}"
        }
    },
    "signature": "0x783f187c775baa8de46a50072f8df3cafe9f39b0ca179bf8b58b41067be0c0722d80829e9e76ae2894f19a0f7c5aca158f716995d03384269a51b1f75a32b6761c",
    "safeAppId": 25
}'`

### PR DESCRIPTION
**Pull request by hectorgomezv**
Closes #439

As I commented in https://github.com/safe-global/safe-client-gateway-nest/issues/439#issuecomment-1597423163, we were validating the Transaction Service response when a message gets created. Based on the OpenAPI definition, we assumed a body containing a `Message` entity would be returned by the Transaction Service but that's not the case. 

This change removes the validation for the payload coming from the Transaction Service when creating a new message.

### CODE REVIEW

File: src/domain/messages/messages.repository.ts [hunk 1]
```diff
@@ -46,16 +46,16 @@ export class MessagesRepository implements IMessagesRepository {
     message: unknown,
     safeAppId: number | null,
     signature: string,
-  ): Promise<Message> {
+  ): Promise<unknown> {
     const transactionService =
       await this.transactionApiManager.getTransactionApi(chainId);
-    const createdMessage = await transactionService.postMessage(
+
```
Comment (iamacook) [inline src/domain/messages/messages.repository.ts:52]: Nit: can we add a TODO comment explaining why we've removed the validation, linking to the [transaction service issue](https://github.com/safe-global/safe-transaction-service/issues/1517)? We can then revisit this in the future.

**Review by fmrsabino — APPROVED** [review]

File: src/domain/messages/messages.repository.ts (hunk 1 above)
Comment (hectorgomezv) [reply src/domain/messages/messages.repository.ts:52]: Yes, I agree with @fmrsabino but I appreciate your suggestion @iamacook 🙂 Also, I think having the Transaction Service documentation issue linked here helps to maintain the traceability just in case some doubt related to this appears in the future.
